version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
  django: &django
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    volumes:
      - .:/django
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  type_check:
    <<: *django
    depends_on:
      - django
    profiles:
      - test
    command: mypy .

  unit_test:
    <<: *django
    depends_on:
      - django
    profiles:
      - test
    command: python manage.py test

  e2e_test:
    <<: *django
    depends_on:
      - django
    profiles:
      - test
    command: python manage.py behave

volumes:
  postgres_data: